apiVersion: v1
kind: Namespace
metadata:
  name: gloo-mesh
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: gloo-platform
  namespace: gloo-mesh
spec:
  interval: 1h
  url: https://storage.googleapis.com/gloo-platform/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gloo-platform
  namespace: gloo-mesh
spec:
  interval: 5m
  chart:
    spec:
      chart: gloo-platform
      version: 2.4.3
      sourceRef:
        kind: HelmRepository
        name: gloo-platform
        namespace: gloo-mesh
      interval: 1m
  values:
    installCRDs: true
    common.cluster: gloo-cluster1

